server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console.enabled: true

cancellation.window: 2